/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.110
 * Generated at: 2025-11-04 02:38:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- 반응형 웹 설정 -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>SUPPHOTO - 로그인</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./assets/css/login.css\">\r\n");
      out.write("<!-- Font Awesome CDN -> 아이콘 사용 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"login-container\">\r\n");
      out.write("		<header class=\"logo\">\r\n");
      out.write("			<h1>SUPPHOTO</h1>\r\n");
      out.write("			<p>얼굴만 찍어,</p>\r\n");
      out.write("			<p>나머진 서포토가 해줄게</p>\r\n");
      out.write("		</header>\r\n");
      out.write("\r\n");
      out.write("		<form class=\"login-form\">\r\n");
      out.write("			<div class=\"input-group\">\r\n");
      out.write("				<label for=\"username\"> <i class=\"fas fa-user\"></i> 아이디\r\n");
      out.write("				</label> <input type=\"text\" id=\"username\" placeholder=\"아이디를 입력해 주세요.\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"input-group password-group\">\r\n");
      out.write("				<label for=\"password\"> <i class=\"fas fa-lock\"></i> 비밀번호\r\n");
      out.write("				</label>\r\n");
      out.write("				<div class=\"password-input-wrapper\">\r\n");
      out.write("					<input type=\"password\" id=\"password\" placeholder=\"비밀번호를 입력해 주세요.\">\r\n");
      out.write("					<button type=\"button\" class=\"show-password-btn\">비밀번호 표시</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<button type=\"submit\" class=\"login-btn\">로그인</button>\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"link-footer\">\r\n");
      out.write("			<a href=\"\">아이디 찾기</a> <span>|</span> <a href=\"\">비밀번호 찾기</a> <span>|</span>\r\n");
      out.write("			<a href=\"Gojoin.do\">회원가입</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- fas (solid) , fab (brands) -->\r\n");
      out.write("		<div class=\"social-login\">\r\n");
      out.write("			<button class=\"social-icon naver\" onclick=\"location.href='NaverLogin.do'\">\r\n");
      out.write("				<img src=\"./assets/img/n-logo.png\" alt=\"Naver Logo\" class=\"social-img\" style=\"border-radius:50%;\">\r\n");
      out.write("			</button>\r\n");
      out.write("			<button class=\"social-icon kakao\" href=\"KakaoLogin.do\">\r\n");
      out.write("				<i class=\"fas fa-comment\"></i>\r\n");
      out.write("			</button>\r\n");
      out.write("			<button class=\"social-icon google\" href=\"GoogleLogin.do\">\r\n");
      out.write("				<img src=\"./assets/img/g-logo.png\" alt=\"Google Logo\" class=\"social-img\">\r\n");
      out.write("			</button>\r\n");
      out.write("			<a href=\"\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<script src=\"./assets/js/login.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
