/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.110
 * Generated at: 2025-11-05 00:10:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class social_002djoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>SUPPHOTO - 회원가입 약관</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/join.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"join-box\">\r\n");
      out.write("        <div class=\"join-wrap\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"join-container\">\r\n");
      out.write("        <header class=\"header\">\r\n");
      out.write("            <h1>회원가입</h1>\r\n");
      out.write("            <a href=\"Gologin.do\">취소</a>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"logo\">\r\n");
      out.write("            <img class=\"join-img\" src=\"./assets/img/join-img.png\">\r\n");
      out.write("            <h1>SUPPHOTO</h1>\r\n");
      out.write("            <p>얼굴만 찍어,</p>\r\n");
      out.write("            <p>나머진 서포토가 해줄게</p>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"join-agree\">\r\n");
      out.write("            <h2><i class=\"fas fa-file-alt\"></i> 서포토 서비스 이용약관</h2>\r\n");
      out.write("            <div class=\"join-agree-list\">\r\n");
      out.write("                <label class=\"all-agree\">\r\n");
      out.write("                    <input type=\"checkbox\" id=\"all-agree-check\" class=\"checkbox\">\r\n");
      out.write("                    <span class=\"check-icon\"><i class=\"fas fa-check-circle\"></i></span>\r\n");
      out.write("                    모두 동의 (선택정보 포함)\r\n");
      out.write("                </label>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"divider\"></div>\r\n");
      out.write("\r\n");
      out.write("                <label class=\"label required\">\r\n");
      out.write("                    <input type=\"checkbox\" class=\"checkbox required\">\r\n");
      out.write("                    <span class=\"check-icon\"><i class=\"fas fa-check-circle\"></i></span>\r\n");
      out.write("                    서비스 이용약관 동의 (필수)\r\n");
      out.write("                    <button type=\"button\" class=\"view-btn\">보기</button>\r\n");
      out.write("                </label>\r\n");
      out.write("\r\n");
      out.write("                <label class=\"label required\">\r\n");
      out.write("                    <input type=\"checkbox\" class=\"checkbox required\">\r\n");
      out.write("                    <span class=\"check-icon\"><i class=\"fas fa-check-circle\"></i></span>\r\n");
      out.write("                    개인정보 수집 및 이용 동의 (필수)\r\n");
      out.write("                    <button type=\"button\" class=\"view-btn\">보기</button>\r\n");
      out.write("                </label>\r\n");
      out.write("\r\n");
      out.write("                <label class=\"label option\">\r\n");
      out.write("                    <input type=\"checkbox\" class=\"checkbox option\">\r\n");
      out.write("                    <span class=\"check-icon\"><i class=\"fas fa-check-circle\"></i></span>\r\n");
      out.write("                    위치기반 서비스 이용약관 동의 (선택)\r\n");
      out.write("                    <button type=\"button\" class=\"view-btn\">보기</button>\r\n");
      out.write("                </label>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("            <button type=\"button\" class=\"next-btn\" id=\"next-btn\" disabled>다음<i\r\n");
      out.write("                    class=\"fas fa-chevron-right\"></i></button>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"join-container\">\r\n");
      out.write("        <header class=\"header\"  style=\"justify-content: flex-start;\">\r\n");
      out.write("            <div class=\"back-btn\">\r\n");
      out.write("                <i class=\"fas fa-chevron-left\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h1>회원가입 정보 입력</h1>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"join-form\">\r\n");
      out.write("            <form action=\"SocialJoin.do\" method=\"post\">\r\n");
      out.write("            	<input type=\"hidden\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("    			<input type=\"hidden\" name=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("    			<input type=\"hidden\" name=\"social_type\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.social_type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                <div class=\"input-group phone-group\">\r\n");
      out.write("                    <label for=\"phone-number\"><i class=\"fas fa-mobile-alt\"></i> 휴대폰 번호 인증</label>\r\n");
      out.write("                    <div class=\"phone-input-wrap\">\r\n");
      out.write("                        <input type=\"text\" id=\"phone-number\" name=\"phone\" placeholder=\"휴대폰 번호 입력(-를 빼고 입력해주세요)\" required>\r\n");
      out.write("                        <button type=\"button\" class=\"send-code-btn\" id=\"send-code-btn\">인증번호 전송</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group verification-code-group\" id=\"verification-code-section\">\r\n");
      out.write("                    <label for=\"verification-code\"><i class=\"fas fa-key\"></i> 인증번호</label>\r\n");
      out.write("                    <div class=\"code-input-wrap\">\r\n");
      out.write("                        <input type=\"text\" id=\"verification-code\" placeholder=\"인증번호 6자리를 입력해 주세요.\" required>\r\n");
      out.write("                        <span class=\"timer\" id=\"timer-display\">05:00</span>\r\n");
      out.write("                        <button type=\"button\" class=\"verify-code-btn\" disabled>확인</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p id=\"verify-Message\" style=\"color:red; font-size:12px;\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"submit\" class=\"submit-btn\" disabled>회원가입</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"./assets/js/socialJoin.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
